baseURL = 'https://blog.tyrol.social/'
languageCode = 'de-de'
title = 'tyrol.social | Blog'
theme = 'paper'

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon